var annotated_dup =
[
    [ "Managers", "namespace_managers.html", null ],
    [ "Book", "class_book.html", "class_book" ],
    [ "BookCollection", "class_book_collection.html", "class_book_collection" ],
    [ "Collection", "class_collection.html", "class_collection" ],
    [ "Company", "class_company.html", "class_company" ],
    [ "Date", "class_date.html", "class_date" ],
    [ "DuplicateElement", "class_duplicate_element.html", "class_duplicate_element" ],
    [ "Employee", "class_employee.html", "class_employee" ],
    [ "Form", "class_form.html", "class_form" ],
    [ "FormEntry", "struct_form_entry.html", "struct_form_entry" ],
    [ "FormOptions", "struct_form_options.html", "struct_form_options" ],
    [ "Input", "struct_input.html", "struct_input" ],
    [ "InputReader", "class_input_reader.html", null ],
    [ "InvalidDate", "struct_invalid_date.html", "struct_invalid_date" ],
    [ "LocalPublication", "class_local_publication.html", "class_local_publication" ],
    [ "Magazine", "class_magazine.html", "class_magazine" ],
    [ "MagazineCollection", "class_magazine_collection.html", "class_magazine_collection" ],
    [ "MalformedFileItem", "class_malformed_file_item.html", "class_malformed_file_item" ],
    [ "ManagerData", "struct_manager_data.html", "struct_manager_data" ],
    [ "Menu", "class_menu.html", "class_menu" ],
    [ "NameNotFound", "class_name_not_found.html", "class_name_not_found" ],
    [ "NonExistentElement", "class_non_existent_element.html", "class_non_existent_element" ],
    [ "Page", "class_page.html", "class_page" ],
    [ "PComp", "struct_p_comp.html", "struct_p_comp" ],
    [ "Publication", "class_publication.html", "class_publication" ],
    [ "Request", "class_request.html", "class_request" ],
    [ "Store", "class_store.html", "class_store" ],
    [ "Suspended", "class_suspended.html", "class_suspended" ],
    [ "suspendedHash", "structsuspended_hash.html", "structsuspended_hash" ],
    [ "Table", "class_table.html", "class_table" ],
    [ "TableEntry", "struct_table_entry.html", "struct_table_entry" ],
    [ "TableOptions", "struct_table_options.html", "struct_table_options" ],
    [ "Token", "struct_token.html", "struct_token" ]
];